Page Object Model
alejandro-bp/cypress-training pull request #7
Opened 2022-07-15 02:28 UTC by alejandro-bp

PR for POM from cypress workshop

2022-07-15 13:22 UTC, manuelq12 requested changes

2022-07-15 13:22 UTC, manuelq12 commented on cypress/e2e/buy-shirt.cy.ts
> +    shippingStepPage.acceptTemrs();
Typo, acceptTerms*

2022-07-15 13:22 UTC, manuelq12 commented on cypress/e2e/buy-shirt.cy.ts
> +    paymentStepPage.orderConfirmations();
The assertions should be done in the cy.js file

My suggestion is to retrieve the element on the Page Object and assert it on the test file

2022-07-18 14:52 UTC, holgiosalos commented on cypress/e2e/buy-shirt.cy.ts
> +    paymentStepPage.paymentMethods();
I will rename the method as `selectBankWire` or `payByBankWire` etc

2022-07-19 05:46 UTC, holgiosalos approved these changes

2022-07-19 13:57 UTC, merged